In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/extrovert-vs-introvert-behavior-data/personality_datasert.csv
/kaggle/input/extrovert-vs-introvert-behavior-data/personality_dataset.csv
/kaggle/input/playground-series-s5e7/sample_submission.csv
/kaggle/input/playground-series-s5e7/train.csv
/kaggle/input/playground-series-s5e7/test.csv

In [2]:
test_df = pd.read_csv('/kaggle/input/playground-series-s5e7/test.csv')
test_df.head()

train_df = pd.read_csv('/kaggle/input/playground-series-s5e7/train.csv') 
train_datasert = pd.read_csv('/kaggle/input/extrovert-vs-introvert-behavior-data/personality_datasert.csv')
train_dataset = pd.read_csv('/kaggle/input/extrovert-vs-introvert-behavior-data/personality_dataset.csv')

train_df.tail()

,id,Time_spent_Alone,Stage_fear,Social_event_attendance,Going_outside,Drained_after_socializing,Friends_circle_size,Post_frequency,Personality
18519,18519,3.0,No,7.0,3.0,No,9.0,7.0,Extrovert
18520,18520,1.0,NaN,6.0,7.0,No,6.0,5.0,Extrovert
18521,18521,7.0,Yes,1.0,1.0,Yes,1.0,NaN,Introvert
18522,18522,NaN,Yes,1.0,0.0,Yes,5.0,2.0,Introvert
18523,18523,1.0,No,8.0,6.0,No,4.0,7.0,Extrovert

In [3]:
train_datasert = train_datasert.rename(columns = {'Personality':'match_p'}).drop_duplicates(['Time_spent_Alone','Stage_fear','Social_event_attendance','Going_outside','Drained_after_socializing','Friends_circle_size','Post_frequency'])
train_datasert.head()

,Time_spent_Alone,Stage_fear,Social_event_attendance,Going_outside,Drained_after_socializing,Friends_circle_size,Post_frequency,match_p
0,4.0,No,4.0,6.0,No,13.0,5.0,Extrovert
1,9.0,Yes,0.0,0.0,Yes,0.0,3.0,Introvert
2,9.0,Yes,1.0,2.0,Yes,5.0,2.0,Introvert
3,0.0,No,6.0,7.0,No,14.0,8.0,Extrovert
4,3.0,No,9.0,4.0,No,8.0,5.0,Extrovert

In [4]:
train_datasert.shape

(2439, 8)

In [5]:
train_dataset = train_dataset.rename(columns= {'Personality':'match_p'}).drop_duplicates(['Time_spent_Alone','Stage_fear','Social_event_attendance','Going_outside','Drained_after_socializing','Friends_circle_size','Post_frequency'])
train_dataset.head()

,Time_spent_Alone,Stage_fear,Social_event_attendance,Going_outside,Drained_after_socializing,Friends_circle_size,Post_frequency,match_p
0,4.0,No,4.0,6.0,No,13.0,5.0,Extrovert
1,9.0,Yes,0.0,0.0,Yes,0.0,3.0,Introvert
2,9.0,Yes,1.0,2.0,Yes,5.0,2.0,Introvert
3,0.0,No,6.0,7.0,No,14.0,8.0,Extrovert
4,3.0,No,9.0,4.0,No,8.0,5.0,Extrovert

In [6]:
# now lets concate both external datasets

external_df = pd.concat([train_datasert,train_dataset],ignore_index=True)
external_df.drop_duplicates(['Time_spent_Alone','Stage_fear','Social_event_attendance','Going_outside','Drained_after_socializing','Friends_circle_size','Post_frequency'],inplace=True)

In [7]:
train_df.head()

,id,Time_spent_Alone,Stage_fear,Social_event_attendance,Going_outside,Drained_after_socializing,Friends_circle_size,Post_frequency,Personality
0,0,0.0,No,6.0,4.0,No,15.0,5.0,Extrovert
1,1,1.0,No,7.0,3.0,No,10.0,8.0,Extrovert
2,2,6.0,Yes,1.0,0.0,NaN,3.0,0.0,Introvert
3,3,3.0,No,7.0,3.0,No,11.0,5.0,Extrovert
4,4,1.0,No,4.0,4.0,No,13.0,NaN,Extrovert

In [8]:
merge_on = ['Time_spent_Alone','Stage_fear','Social_event_attendance','Going_outside','Drained_after_socializing','Friends_circle_size','Post_frequency']


train_df = train_df.merge(external_df,on=merge_on,how='left')
test_df = test_df.merge(external_df,on=merge_on,how='left')

In [9]:
train_df.head()

# removing id col

train_df.drop('id',axis=1,inplace=True)

In [10]:
test_df.head()

,id,Time_spent_Alone,Stage_fear,Social_event_attendance,Going_outside,Drained_after_socializing,Friends_circle_size,Post_frequency,match_p
0,18524,3.0,No,7.0,4.0,No,6.0,NaN,NaN
1,18525,NaN,Yes,0.0,0.0,Yes,5.0,1.0,NaN
2,18526,3.0,No,5.0,6.0,No,15.0,9.0,NaN
3,18527,3.0,No,4.0,4.0,No,5.0,6.0,NaN
4,18528,9.0,Yes,1.0,2.0,Yes,1.0,1.0,NaN

In [11]:
train_df.head()

,Time_spent_Alone,Stage_fear,Social_event_attendance,Going_outside,Drained_after_socializing,Friends_circle_size,Post_frequency,Personality,match_p
0,0.0,No,6.0,4.0,No,15.0,5.0,Extrovert,NaN
1,1.0,No,7.0,3.0,No,10.0,8.0,Extrovert,NaN
2,6.0,Yes,1.0,0.0,NaN,3.0,0.0,Introvert,NaN
3,3.0,No,7.0,3.0,No,11.0,5.0,Extrovert,NaN
4,1.0,No,4.0,4.0,No,13.0,NaN,Extrovert,NaN

In [12]:
target = train_df['Personality']
train_df.drop('Personality',axis=1,inplace=True)
num_cols = train_df.select_dtypes(include=['float64']).columns
cat_cols = train_df.select_dtypes(include=['object']).columns

In [13]:
from sklearn.impute import SimpleImputer 

SI = SimpleImputer(strategy='median')

train_df[num_cols] = SI.fit_transform(train_df[num_cols])
test_df[num_cols] = SI.transform(test_df[num_cols])

In [14]:
SI = SimpleImputer(strategy='most_frequent')

train_df[cat_cols] = SI.fit_transform(train_df[cat_cols])
test_df[cat_cols] = SI.transform(test_df[cat_cols])

In [15]:
train_df.head()

,Time_spent_Alone,Stage_fear,Social_event_attendance,Going_outside,Drained_after_socializing,Friends_circle_size,Post_frequency,match_p
0,0.0,No,6.0,4.0,No,15.0,5.0,Extrovert
1,1.0,No,7.0,3.0,No,10.0,8.0,Extrovert
2,6.0,Yes,1.0,0.0,No,3.0,0.0,Extrovert
3,3.0,No,7.0,3.0,No,11.0,5.0,Extrovert
4,1.0,No,4.0,4.0,No,13.0,5.0,Extrovert

In [16]:
# now lets do one hot encoding to see whether we are getting the better score or not

In [17]:
from sklearn.preprocessing import OneHotEncoder 

encoder = OneHotEncoder(drop ='first',sparse_output=False) 

enc_array = (encoder.fit_transform(train_df[cat_cols]))
enc_array_test = encoder.transform(test_df[cat_cols])
enc_df = pd.DataFrame(enc_array,columns = encoder.get_feature_names_out(cat_cols),index = train_df.index)
enc_df_test = pd.DataFrame(enc_array_test,columns = encoder.get_feature_names_out(cat_cols),index=test_df.index)


train_df.drop(columns = cat_cols,inplace=True,axis=1)
test_df.drop(columns=cat_cols,inplace=True,axis=1)

In [18]:
train_df.head()

train_df = pd.concat([train_df,enc_df],axis=1)
test_df = pd.concat([test_df,enc_df_test],axis=1)
train_df.head()
test_df.head()

,id,Time_spent_Alone,Social_event_attendance,Going_outside,Friends_circle_size,Post_frequency,Stage_fear_Yes,Drained_after_socializing_Yes,match_p_Introvert
0,18524,3.0,7.0,4.0,6.0,5.0,0.0,0.0,0.0
1,18525,2.0,0.0,0.0,5.0,1.0,1.0,1.0,0.0
2,18526,3.0,5.0,6.0,15.0,9.0,0.0,0.0,0.0
3,18527,3.0,4.0,4.0,5.0,6.0,0.0,0.0,0.0
4,18528,9.0,1.0,2.0,1.0,1.0,1.0,1.0,0.0

In [19]:
test_ids = test_df['id']
test_ids

0       18524
1       18525
2       18526
3       18527
4       18528
        ...
6170    24694
6171    24695
6172    24696
6173    24697
6174    24698
Name: id, Length: 6175, dtype: int64

In [20]:
test_df.drop('id',axis=1,inplace=True)

In [21]:
X = train_df
y = target

In [22]:
y = y.map({'Extrovert':0,'Introvert':1})

In [23]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

In [24]:
from xgboost import XGBClassifier

In [25]:
X.head()

,Time_spent_Alone,Social_event_attendance,Going_outside,Friends_circle_size,Post_frequency,Stage_fear_Yes,Drained_after_socializing_Yes,match_p_Introvert
0,0.0,6.0,4.0,15.0,5.0,0.0,0.0,0.0
1,1.0,7.0,3.0,10.0,8.0,0.0,0.0,0.0
2,6.0,1.0,0.0,3.0,0.0,1.0,0.0,0.0
3,3.0,7.0,3.0,11.0,5.0,0.0,0.0,0.0
4,1.0,4.0,4.0,13.0,5.0,0.0,0.0,0.0

In [26]:
from sklearn.ensemble import GradientBoostingClassifier

GB = GradientBoostingClassifier()
GB.fit(X_train,y_train)
y_pred = GB.predict(X_test)
print('accuracy',accuracy_score(y_test, y_pred))

accuracy 0.9727395411605938

In [27]:
y_arr = pd.Series(GB.predict(test_df))

y_test = y_arr.map({0:'Extrovert',1:'Introvert'}) 
y_test.head()

0    Extrovert
1    Introvert
2    Extrovert
3    Extrovert
4    Introvert
dtype: object

In [28]:
sample = pd.read_csv('/kaggle/input/playground-series-s5e7/sample_submission.csv')
sample.head()

      id Personality
0  18524   Extrovert
1  18525   Extrovert
2  18526   Extrovert
3  18527   Extrovert
4  18528   Extrovert

In [29]:
submission = pd.DataFrame({'id':test_ids,
              'Personality':y_test 
})
submission.head()

      id Personality
0  18524   Extrovert
1  18525   Introvert
2  18526   Extrovert
3  18527   Extrovert
4  18528   Introvert

In [30]:
submission.to_csv('submission.csv',index=False)